//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.DADashboardLogSoap")]
    public interface DADashboardLogSoap {
        
        // CODEGEN: Generating message contract since element name robotName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/STAT", ReplyAction="*")]
        Task.ServiceReference2.STATResponse STAT(Task.ServiceReference2.STATRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/STAT", ReplyAction="*")]
        System.Threading.Tasks.Task<Task.ServiceReference2.STATResponse> STATAsync(Task.ServiceReference2.STATRequest request);
        
        // CODEGEN: Generating message contract since element name robotName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/STAT2", ReplyAction="*")]
        Task.ServiceReference2.STAT2Response STAT2(Task.ServiceReference2.STAT2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/STAT2", ReplyAction="*")]
        System.Threading.Tasks.Task<Task.ServiceReference2.STAT2Response> STAT2Async(Task.ServiceReference2.STAT2Request request);
        
        // CODEGEN: Generating message contract since element name robotName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VERSION", ReplyAction="*")]
        Task.ServiceReference2.VERSIONResponse VERSION(Task.ServiceReference2.VERSIONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VERSION", ReplyAction="*")]
        System.Threading.Tasks.Task<Task.ServiceReference2.VERSIONResponse> VERSIONAsync(Task.ServiceReference2.VERSIONRequest request);
        
        // CODEGEN: Generating message contract since element name robotName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ERROR", ReplyAction="*")]
        Task.ServiceReference2.ERRORResponse ERROR(Task.ServiceReference2.ERRORRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ERROR", ReplyAction="*")]
        System.Threading.Tasks.Task<Task.ServiceReference2.ERRORResponse> ERRORAsync(Task.ServiceReference2.ERRORRequest request);
        
        // CODEGEN: Generating message contract since element name robotName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WARNING", ReplyAction="*")]
        Task.ServiceReference2.WARNINGResponse WARNING(Task.ServiceReference2.WARNINGRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WARNING", ReplyAction="*")]
        System.Threading.Tasks.Task<Task.ServiceReference2.WARNINGResponse> WARNINGAsync(Task.ServiceReference2.WARNINGRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class STATRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="STAT", Namespace="http://tempuri.org/", Order=0)]
        public Task.ServiceReference2.STATRequestBody Body;
        
        public STATRequest() {
        }
        
        public STATRequest(Task.ServiceReference2.STATRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class STATRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string robotName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string client;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string program;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string region;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string site;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string workstation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string lANID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string lANIDFor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string dATA01;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string dATA02;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string dATA03;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string dATA04;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string dATA05;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string dATA06;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string dATA07;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string dATA08;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string dATA09;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string dATA10;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public System.Nullable<double> sTAT01;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public System.Nullable<double> sTAT02;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public System.Nullable<double> sTAT03;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public System.Nullable<double> sTAT04;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=22)]
        public System.Nullable<double> sTAT05;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=23)]
        public System.Nullable<double> sTAT06;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=24)]
        public System.Nullable<double> sTAT07;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=25)]
        public System.Nullable<double> sTAT08;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=26)]
        public System.Nullable<double> sTAT09;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=27)]
        public System.Nullable<double> sTAT10;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string note;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public string lastUpdateBy;
        
        public STATRequestBody() {
        }
        
        public STATRequestBody(
                    string robotName, 
                    string client, 
                    string program, 
                    string region, 
                    string site, 
                    string workstation, 
                    string lANID, 
                    string lANIDFor, 
                    string dATA01, 
                    string dATA02, 
                    string dATA03, 
                    string dATA04, 
                    string dATA05, 
                    string dATA06, 
                    string dATA07, 
                    string dATA08, 
                    string dATA09, 
                    string dATA10, 
                    System.Nullable<double> sTAT01, 
                    System.Nullable<double> sTAT02, 
                    System.Nullable<double> sTAT03, 
                    System.Nullable<double> sTAT04, 
                    System.Nullable<double> sTAT05, 
                    System.Nullable<double> sTAT06, 
                    System.Nullable<double> sTAT07, 
                    System.Nullable<double> sTAT08, 
                    System.Nullable<double> sTAT09, 
                    System.Nullable<double> sTAT10, 
                    string note, 
                    string lastUpdateBy) {
            this.robotName = robotName;
            this.client = client;
            this.program = program;
            this.region = region;
            this.site = site;
            this.workstation = workstation;
            this.lANID = lANID;
            this.lANIDFor = lANIDFor;
            this.dATA01 = dATA01;
            this.dATA02 = dATA02;
            this.dATA03 = dATA03;
            this.dATA04 = dATA04;
            this.dATA05 = dATA05;
            this.dATA06 = dATA06;
            this.dATA07 = dATA07;
            this.dATA08 = dATA08;
            this.dATA09 = dATA09;
            this.dATA10 = dATA10;
            this.sTAT01 = sTAT01;
            this.sTAT02 = sTAT02;
            this.sTAT03 = sTAT03;
            this.sTAT04 = sTAT04;
            this.sTAT05 = sTAT05;
            this.sTAT06 = sTAT06;
            this.sTAT07 = sTAT07;
            this.sTAT08 = sTAT08;
            this.sTAT09 = sTAT09;
            this.sTAT10 = sTAT10;
            this.note = note;
            this.lastUpdateBy = lastUpdateBy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class STATResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="STATResponse", Namespace="http://tempuri.org/", Order=0)]
        public Task.ServiceReference2.STATResponseBody Body;
        
        public STATResponse() {
        }
        
        public STATResponse(Task.ServiceReference2.STATResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class STATResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string STATResult;
        
        public STATResponseBody() {
        }
        
        public STATResponseBody(string STATResult) {
            this.STATResult = STATResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class STAT2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="STAT2", Namespace="http://tempuri.org/", Order=0)]
        public Task.ServiceReference2.STAT2RequestBody Body;
        
        public STAT2Request() {
        }
        
        public STAT2Request(Task.ServiceReference2.STAT2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class STAT2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string robotName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string client;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string program;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string region;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string site;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string workstation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string lANID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string lANIDFor;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.Nullable<double> tXCOUNT;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.Nullable<double> tXSUCCESS;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public System.Nullable<double> tXFAILED;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public System.Nullable<int> tXTIME;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string dATA01;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string dATA02;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string dATA03;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string dATA04;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string dATA05;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string dATA06;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string dATA07;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string dATA08;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string dATA09;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string dATA10;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=22)]
        public System.Nullable<double> sTAT01;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=23)]
        public System.Nullable<double> sTAT02;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=24)]
        public System.Nullable<double> sTAT03;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=25)]
        public System.Nullable<double> sTAT04;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=26)]
        public System.Nullable<double> sTAT05;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=27)]
        public System.Nullable<double> sTAT06;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=28)]
        public System.Nullable<double> sTAT07;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=29)]
        public System.Nullable<double> sTAT08;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=30)]
        public System.Nullable<double> sTAT09;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=31)]
        public System.Nullable<double> sTAT10;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=32)]
        public string note;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=33)]
        public string lastUpdateBy;
        
        public STAT2RequestBody() {
        }
        
        public STAT2RequestBody(
                    string robotName, 
                    string client, 
                    string program, 
                    string region, 
                    string site, 
                    string workstation, 
                    string lANID, 
                    string lANIDFor, 
                    System.Nullable<double> tXCOUNT, 
                    System.Nullable<double> tXSUCCESS, 
                    System.Nullable<double> tXFAILED, 
                    System.Nullable<int> tXTIME, 
                    string dATA01, 
                    string dATA02, 
                    string dATA03, 
                    string dATA04, 
                    string dATA05, 
                    string dATA06, 
                    string dATA07, 
                    string dATA08, 
                    string dATA09, 
                    string dATA10, 
                    System.Nullable<double> sTAT01, 
                    System.Nullable<double> sTAT02, 
                    System.Nullable<double> sTAT03, 
                    System.Nullable<double> sTAT04, 
                    System.Nullable<double> sTAT05, 
                    System.Nullable<double> sTAT06, 
                    System.Nullable<double> sTAT07, 
                    System.Nullable<double> sTAT08, 
                    System.Nullable<double> sTAT09, 
                    System.Nullable<double> sTAT10, 
                    string note, 
                    string lastUpdateBy) {
            this.robotName = robotName;
            this.client = client;
            this.program = program;
            this.region = region;
            this.site = site;
            this.workstation = workstation;
            this.lANID = lANID;
            this.lANIDFor = lANIDFor;
            this.tXCOUNT = tXCOUNT;
            this.tXSUCCESS = tXSUCCESS;
            this.tXFAILED = tXFAILED;
            this.tXTIME = tXTIME;
            this.dATA01 = dATA01;
            this.dATA02 = dATA02;
            this.dATA03 = dATA03;
            this.dATA04 = dATA04;
            this.dATA05 = dATA05;
            this.dATA06 = dATA06;
            this.dATA07 = dATA07;
            this.dATA08 = dATA08;
            this.dATA09 = dATA09;
            this.dATA10 = dATA10;
            this.sTAT01 = sTAT01;
            this.sTAT02 = sTAT02;
            this.sTAT03 = sTAT03;
            this.sTAT04 = sTAT04;
            this.sTAT05 = sTAT05;
            this.sTAT06 = sTAT06;
            this.sTAT07 = sTAT07;
            this.sTAT08 = sTAT08;
            this.sTAT09 = sTAT09;
            this.sTAT10 = sTAT10;
            this.note = note;
            this.lastUpdateBy = lastUpdateBy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class STAT2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="STAT2Response", Namespace="http://tempuri.org/", Order=0)]
        public Task.ServiceReference2.STAT2ResponseBody Body;
        
        public STAT2Response() {
        }
        
        public STAT2Response(Task.ServiceReference2.STAT2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class STAT2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string STAT2Result;
        
        public STAT2ResponseBody() {
        }
        
        public STAT2ResponseBody(string STAT2Result) {
            this.STAT2Result = STAT2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VERSIONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VERSION", Namespace="http://tempuri.org/", Order=0)]
        public Task.ServiceReference2.VERSIONRequestBody Body;
        
        public VERSIONRequest() {
        }
        
        public VERSIONRequest(Task.ServiceReference2.VERSIONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VERSIONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string robotName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string client;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string program;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string region;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string site;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string workstation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string lANID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string dATA01;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string lastUpdateBy;
        
        public VERSIONRequestBody() {
        }
        
        public VERSIONRequestBody(string robotName, string client, string program, string region, string site, string workstation, string lANID, string dATA01, string lastUpdateBy) {
            this.robotName = robotName;
            this.client = client;
            this.program = program;
            this.region = region;
            this.site = site;
            this.workstation = workstation;
            this.lANID = lANID;
            this.dATA01 = dATA01;
            this.lastUpdateBy = lastUpdateBy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VERSIONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VERSIONResponse", Namespace="http://tempuri.org/", Order=0)]
        public Task.ServiceReference2.VERSIONResponseBody Body;
        
        public VERSIONResponse() {
        }
        
        public VERSIONResponse(Task.ServiceReference2.VERSIONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VERSIONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VERSIONResult;
        
        public VERSIONResponseBody() {
        }
        
        public VERSIONResponseBody(string VERSIONResult) {
            this.VERSIONResult = VERSIONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ERRORRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ERROR", Namespace="http://tempuri.org/", Order=0)]
        public Task.ServiceReference2.ERRORRequestBody Body;
        
        public ERRORRequest() {
        }
        
        public ERRORRequest(Task.ServiceReference2.ERRORRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ERRORRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string robotName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string client;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string program;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string region;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string site;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string workstation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string lANID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string dATA01;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string lastUpdateBy;
        
        public ERRORRequestBody() {
        }
        
        public ERRORRequestBody(string robotName, string client, string program, string region, string site, string workstation, string lANID, string dATA01, string lastUpdateBy) {
            this.robotName = robotName;
            this.client = client;
            this.program = program;
            this.region = region;
            this.site = site;
            this.workstation = workstation;
            this.lANID = lANID;
            this.dATA01 = dATA01;
            this.lastUpdateBy = lastUpdateBy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ERRORResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ERRORResponse", Namespace="http://tempuri.org/", Order=0)]
        public Task.ServiceReference2.ERRORResponseBody Body;
        
        public ERRORResponse() {
        }
        
        public ERRORResponse(Task.ServiceReference2.ERRORResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ERRORResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ERRORResult;
        
        public ERRORResponseBody() {
        }
        
        public ERRORResponseBody(string ERRORResult) {
            this.ERRORResult = ERRORResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WARNINGRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WARNING", Namespace="http://tempuri.org/", Order=0)]
        public Task.ServiceReference2.WARNINGRequestBody Body;
        
        public WARNINGRequest() {
        }
        
        public WARNINGRequest(Task.ServiceReference2.WARNINGRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WARNINGRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string robotName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string client;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string program;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string region;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string site;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string workstation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string lANID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string dATA01;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string lastUpdateBy;
        
        public WARNINGRequestBody() {
        }
        
        public WARNINGRequestBody(string robotName, string client, string program, string region, string site, string workstation, string lANID, string dATA01, string lastUpdateBy) {
            this.robotName = robotName;
            this.client = client;
            this.program = program;
            this.region = region;
            this.site = site;
            this.workstation = workstation;
            this.lANID = lANID;
            this.dATA01 = dATA01;
            this.lastUpdateBy = lastUpdateBy;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WARNINGResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WARNINGResponse", Namespace="http://tempuri.org/", Order=0)]
        public Task.ServiceReference2.WARNINGResponseBody Body;
        
        public WARNINGResponse() {
        }
        
        public WARNINGResponse(Task.ServiceReference2.WARNINGResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WARNINGResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WARNINGResult;
        
        public WARNINGResponseBody() {
        }
        
        public WARNINGResponseBody(string WARNINGResult) {
            this.WARNINGResult = WARNINGResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DADashboardLogSoapChannel : Task.ServiceReference2.DADashboardLogSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DADashboardLogSoapClient : System.ServiceModel.ClientBase<Task.ServiceReference2.DADashboardLogSoap>, Task.ServiceReference2.DADashboardLogSoap {
        
        public DADashboardLogSoapClient() {
        }
        
        public DADashboardLogSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DADashboardLogSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DADashboardLogSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DADashboardLogSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Task.ServiceReference2.STATResponse Task.ServiceReference2.DADashboardLogSoap.STAT(Task.ServiceReference2.STATRequest request) {
            return base.Channel.STAT(request);
        }
        
        public string STAT(
                    string robotName, 
                    string client, 
                    string program, 
                    string region, 
                    string site, 
                    string workstation, 
                    string lANID, 
                    string lANIDFor, 
                    string dATA01, 
                    string dATA02, 
                    string dATA03, 
                    string dATA04, 
                    string dATA05, 
                    string dATA06, 
                    string dATA07, 
                    string dATA08, 
                    string dATA09, 
                    string dATA10, 
                    System.Nullable<double> sTAT01, 
                    System.Nullable<double> sTAT02, 
                    System.Nullable<double> sTAT03, 
                    System.Nullable<double> sTAT04, 
                    System.Nullable<double> sTAT05, 
                    System.Nullable<double> sTAT06, 
                    System.Nullable<double> sTAT07, 
                    System.Nullable<double> sTAT08, 
                    System.Nullable<double> sTAT09, 
                    System.Nullable<double> sTAT10, 
                    string note, 
                    string lastUpdateBy) {
            Task.ServiceReference2.STATRequest inValue = new Task.ServiceReference2.STATRequest();
            inValue.Body = new Task.ServiceReference2.STATRequestBody();
            inValue.Body.robotName = robotName;
            inValue.Body.client = client;
            inValue.Body.program = program;
            inValue.Body.region = region;
            inValue.Body.site = site;
            inValue.Body.workstation = workstation;
            inValue.Body.lANID = lANID;
            inValue.Body.lANIDFor = lANIDFor;
            inValue.Body.dATA01 = dATA01;
            inValue.Body.dATA02 = dATA02;
            inValue.Body.dATA03 = dATA03;
            inValue.Body.dATA04 = dATA04;
            inValue.Body.dATA05 = dATA05;
            inValue.Body.dATA06 = dATA06;
            inValue.Body.dATA07 = dATA07;
            inValue.Body.dATA08 = dATA08;
            inValue.Body.dATA09 = dATA09;
            inValue.Body.dATA10 = dATA10;
            inValue.Body.sTAT01 = sTAT01;
            inValue.Body.sTAT02 = sTAT02;
            inValue.Body.sTAT03 = sTAT03;
            inValue.Body.sTAT04 = sTAT04;
            inValue.Body.sTAT05 = sTAT05;
            inValue.Body.sTAT06 = sTAT06;
            inValue.Body.sTAT07 = sTAT07;
            inValue.Body.sTAT08 = sTAT08;
            inValue.Body.sTAT09 = sTAT09;
            inValue.Body.sTAT10 = sTAT10;
            inValue.Body.note = note;
            inValue.Body.lastUpdateBy = lastUpdateBy;
            Task.ServiceReference2.STATResponse retVal = ((Task.ServiceReference2.DADashboardLogSoap)(this)).STAT(inValue);
            return retVal.Body.STATResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Task.ServiceReference2.STATResponse> Task.ServiceReference2.DADashboardLogSoap.STATAsync(Task.ServiceReference2.STATRequest request) {
            return base.Channel.STATAsync(request);
        }
        
        public System.Threading.Tasks.Task<Task.ServiceReference2.STATResponse> STATAsync(
                    string robotName, 
                    string client, 
                    string program, 
                    string region, 
                    string site, 
                    string workstation, 
                    string lANID, 
                    string lANIDFor, 
                    string dATA01, 
                    string dATA02, 
                    string dATA03, 
                    string dATA04, 
                    string dATA05, 
                    string dATA06, 
                    string dATA07, 
                    string dATA08, 
                    string dATA09, 
                    string dATA10, 
                    System.Nullable<double> sTAT01, 
                    System.Nullable<double> sTAT02, 
                    System.Nullable<double> sTAT03, 
                    System.Nullable<double> sTAT04, 
                    System.Nullable<double> sTAT05, 
                    System.Nullable<double> sTAT06, 
                    System.Nullable<double> sTAT07, 
                    System.Nullable<double> sTAT08, 
                    System.Nullable<double> sTAT09, 
                    System.Nullable<double> sTAT10, 
                    string note, 
                    string lastUpdateBy) {
            Task.ServiceReference2.STATRequest inValue = new Task.ServiceReference2.STATRequest();
            inValue.Body = new Task.ServiceReference2.STATRequestBody();
            inValue.Body.robotName = robotName;
            inValue.Body.client = client;
            inValue.Body.program = program;
            inValue.Body.region = region;
            inValue.Body.site = site;
            inValue.Body.workstation = workstation;
            inValue.Body.lANID = lANID;
            inValue.Body.lANIDFor = lANIDFor;
            inValue.Body.dATA01 = dATA01;
            inValue.Body.dATA02 = dATA02;
            inValue.Body.dATA03 = dATA03;
            inValue.Body.dATA04 = dATA04;
            inValue.Body.dATA05 = dATA05;
            inValue.Body.dATA06 = dATA06;
            inValue.Body.dATA07 = dATA07;
            inValue.Body.dATA08 = dATA08;
            inValue.Body.dATA09 = dATA09;
            inValue.Body.dATA10 = dATA10;
            inValue.Body.sTAT01 = sTAT01;
            inValue.Body.sTAT02 = sTAT02;
            inValue.Body.sTAT03 = sTAT03;
            inValue.Body.sTAT04 = sTAT04;
            inValue.Body.sTAT05 = sTAT05;
            inValue.Body.sTAT06 = sTAT06;
            inValue.Body.sTAT07 = sTAT07;
            inValue.Body.sTAT08 = sTAT08;
            inValue.Body.sTAT09 = sTAT09;
            inValue.Body.sTAT10 = sTAT10;
            inValue.Body.note = note;
            inValue.Body.lastUpdateBy = lastUpdateBy;
            return ((Task.ServiceReference2.DADashboardLogSoap)(this)).STATAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Task.ServiceReference2.STAT2Response Task.ServiceReference2.DADashboardLogSoap.STAT2(Task.ServiceReference2.STAT2Request request) {
            return base.Channel.STAT2(request);
        }
        
        public string STAT2(
                    string robotName, 
                    string client, 
                    string program, 
                    string region, 
                    string site, 
                    string workstation, 
                    string lANID, 
                    string lANIDFor, 
                    System.Nullable<double> tXCOUNT, 
                    System.Nullable<double> tXSUCCESS, 
                    System.Nullable<double> tXFAILED, 
                    System.Nullable<int> tXTIME, 
                    string dATA01, 
                    string dATA02, 
                    string dATA03, 
                    string dATA04, 
                    string dATA05, 
                    string dATA06, 
                    string dATA07, 
                    string dATA08, 
                    string dATA09, 
                    string dATA10, 
                    System.Nullable<double> sTAT01, 
                    System.Nullable<double> sTAT02, 
                    System.Nullable<double> sTAT03, 
                    System.Nullable<double> sTAT04, 
                    System.Nullable<double> sTAT05, 
                    System.Nullable<double> sTAT06, 
                    System.Nullable<double> sTAT07, 
                    System.Nullable<double> sTAT08, 
                    System.Nullable<double> sTAT09, 
                    System.Nullable<double> sTAT10, 
                    string note, 
                    string lastUpdateBy) {
            Task.ServiceReference2.STAT2Request inValue = new Task.ServiceReference2.STAT2Request();
            inValue.Body = new Task.ServiceReference2.STAT2RequestBody();
            inValue.Body.robotName = robotName;
            inValue.Body.client = client;
            inValue.Body.program = program;
            inValue.Body.region = region;
            inValue.Body.site = site;
            inValue.Body.workstation = workstation;
            inValue.Body.lANID = lANID;
            inValue.Body.lANIDFor = lANIDFor;
            inValue.Body.tXCOUNT = tXCOUNT;
            inValue.Body.tXSUCCESS = tXSUCCESS;
            inValue.Body.tXFAILED = tXFAILED;
            inValue.Body.tXTIME = tXTIME;
            inValue.Body.dATA01 = dATA01;
            inValue.Body.dATA02 = dATA02;
            inValue.Body.dATA03 = dATA03;
            inValue.Body.dATA04 = dATA04;
            inValue.Body.dATA05 = dATA05;
            inValue.Body.dATA06 = dATA06;
            inValue.Body.dATA07 = dATA07;
            inValue.Body.dATA08 = dATA08;
            inValue.Body.dATA09 = dATA09;
            inValue.Body.dATA10 = dATA10;
            inValue.Body.sTAT01 = sTAT01;
            inValue.Body.sTAT02 = sTAT02;
            inValue.Body.sTAT03 = sTAT03;
            inValue.Body.sTAT04 = sTAT04;
            inValue.Body.sTAT05 = sTAT05;
            inValue.Body.sTAT06 = sTAT06;
            inValue.Body.sTAT07 = sTAT07;
            inValue.Body.sTAT08 = sTAT08;
            inValue.Body.sTAT09 = sTAT09;
            inValue.Body.sTAT10 = sTAT10;
            inValue.Body.note = note;
            inValue.Body.lastUpdateBy = lastUpdateBy;
            Task.ServiceReference2.STAT2Response retVal = ((Task.ServiceReference2.DADashboardLogSoap)(this)).STAT2(inValue);
            return retVal.Body.STAT2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Task.ServiceReference2.STAT2Response> Task.ServiceReference2.DADashboardLogSoap.STAT2Async(Task.ServiceReference2.STAT2Request request) {
            return base.Channel.STAT2Async(request);
        }
        
        public System.Threading.Tasks.Task<Task.ServiceReference2.STAT2Response> STAT2Async(
                    string robotName, 
                    string client, 
                    string program, 
                    string region, 
                    string site, 
                    string workstation, 
                    string lANID, 
                    string lANIDFor, 
                    System.Nullable<double> tXCOUNT, 
                    System.Nullable<double> tXSUCCESS, 
                    System.Nullable<double> tXFAILED, 
                    System.Nullable<int> tXTIME, 
                    string dATA01, 
                    string dATA02, 
                    string dATA03, 
                    string dATA04, 
                    string dATA05, 
                    string dATA06, 
                    string dATA07, 
                    string dATA08, 
                    string dATA09, 
                    string dATA10, 
                    System.Nullable<double> sTAT01, 
                    System.Nullable<double> sTAT02, 
                    System.Nullable<double> sTAT03, 
                    System.Nullable<double> sTAT04, 
                    System.Nullable<double> sTAT05, 
                    System.Nullable<double> sTAT06, 
                    System.Nullable<double> sTAT07, 
                    System.Nullable<double> sTAT08, 
                    System.Nullable<double> sTAT09, 
                    System.Nullable<double> sTAT10, 
                    string note, 
                    string lastUpdateBy) {
            Task.ServiceReference2.STAT2Request inValue = new Task.ServiceReference2.STAT2Request();
            inValue.Body = new Task.ServiceReference2.STAT2RequestBody();
            inValue.Body.robotName = robotName;
            inValue.Body.client = client;
            inValue.Body.program = program;
            inValue.Body.region = region;
            inValue.Body.site = site;
            inValue.Body.workstation = workstation;
            inValue.Body.lANID = lANID;
            inValue.Body.lANIDFor = lANIDFor;
            inValue.Body.tXCOUNT = tXCOUNT;
            inValue.Body.tXSUCCESS = tXSUCCESS;
            inValue.Body.tXFAILED = tXFAILED;
            inValue.Body.tXTIME = tXTIME;
            inValue.Body.dATA01 = dATA01;
            inValue.Body.dATA02 = dATA02;
            inValue.Body.dATA03 = dATA03;
            inValue.Body.dATA04 = dATA04;
            inValue.Body.dATA05 = dATA05;
            inValue.Body.dATA06 = dATA06;
            inValue.Body.dATA07 = dATA07;
            inValue.Body.dATA08 = dATA08;
            inValue.Body.dATA09 = dATA09;
            inValue.Body.dATA10 = dATA10;
            inValue.Body.sTAT01 = sTAT01;
            inValue.Body.sTAT02 = sTAT02;
            inValue.Body.sTAT03 = sTAT03;
            inValue.Body.sTAT04 = sTAT04;
            inValue.Body.sTAT05 = sTAT05;
            inValue.Body.sTAT06 = sTAT06;
            inValue.Body.sTAT07 = sTAT07;
            inValue.Body.sTAT08 = sTAT08;
            inValue.Body.sTAT09 = sTAT09;
            inValue.Body.sTAT10 = sTAT10;
            inValue.Body.note = note;
            inValue.Body.lastUpdateBy = lastUpdateBy;
            return ((Task.ServiceReference2.DADashboardLogSoap)(this)).STAT2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Task.ServiceReference2.VERSIONResponse Task.ServiceReference2.DADashboardLogSoap.VERSION(Task.ServiceReference2.VERSIONRequest request) {
            return base.Channel.VERSION(request);
        }
        
        public string VERSION(string robotName, string client, string program, string region, string site, string workstation, string lANID, string dATA01, string lastUpdateBy) {
            Task.ServiceReference2.VERSIONRequest inValue = new Task.ServiceReference2.VERSIONRequest();
            inValue.Body = new Task.ServiceReference2.VERSIONRequestBody();
            inValue.Body.robotName = robotName;
            inValue.Body.client = client;
            inValue.Body.program = program;
            inValue.Body.region = region;
            inValue.Body.site = site;
            inValue.Body.workstation = workstation;
            inValue.Body.lANID = lANID;
            inValue.Body.dATA01 = dATA01;
            inValue.Body.lastUpdateBy = lastUpdateBy;
            Task.ServiceReference2.VERSIONResponse retVal = ((Task.ServiceReference2.DADashboardLogSoap)(this)).VERSION(inValue);
            return retVal.Body.VERSIONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Task.ServiceReference2.VERSIONResponse> Task.ServiceReference2.DADashboardLogSoap.VERSIONAsync(Task.ServiceReference2.VERSIONRequest request) {
            return base.Channel.VERSIONAsync(request);
        }
        
        public System.Threading.Tasks.Task<Task.ServiceReference2.VERSIONResponse> VERSIONAsync(string robotName, string client, string program, string region, string site, string workstation, string lANID, string dATA01, string lastUpdateBy) {
            Task.ServiceReference2.VERSIONRequest inValue = new Task.ServiceReference2.VERSIONRequest();
            inValue.Body = new Task.ServiceReference2.VERSIONRequestBody();
            inValue.Body.robotName = robotName;
            inValue.Body.client = client;
            inValue.Body.program = program;
            inValue.Body.region = region;
            inValue.Body.site = site;
            inValue.Body.workstation = workstation;
            inValue.Body.lANID = lANID;
            inValue.Body.dATA01 = dATA01;
            inValue.Body.lastUpdateBy = lastUpdateBy;
            return ((Task.ServiceReference2.DADashboardLogSoap)(this)).VERSIONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Task.ServiceReference2.ERRORResponse Task.ServiceReference2.DADashboardLogSoap.ERROR(Task.ServiceReference2.ERRORRequest request) {
            return base.Channel.ERROR(request);
        }
        
        public string ERROR(string robotName, string client, string program, string region, string site, string workstation, string lANID, string dATA01, string lastUpdateBy) {
            Task.ServiceReference2.ERRORRequest inValue = new Task.ServiceReference2.ERRORRequest();
            inValue.Body = new Task.ServiceReference2.ERRORRequestBody();
            inValue.Body.robotName = robotName;
            inValue.Body.client = client;
            inValue.Body.program = program;
            inValue.Body.region = region;
            inValue.Body.site = site;
            inValue.Body.workstation = workstation;
            inValue.Body.lANID = lANID;
            inValue.Body.dATA01 = dATA01;
            inValue.Body.lastUpdateBy = lastUpdateBy;
            Task.ServiceReference2.ERRORResponse retVal = ((Task.ServiceReference2.DADashboardLogSoap)(this)).ERROR(inValue);
            return retVal.Body.ERRORResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Task.ServiceReference2.ERRORResponse> Task.ServiceReference2.DADashboardLogSoap.ERRORAsync(Task.ServiceReference2.ERRORRequest request) {
            return base.Channel.ERRORAsync(request);
        }
        
        public System.Threading.Tasks.Task<Task.ServiceReference2.ERRORResponse> ERRORAsync(string robotName, string client, string program, string region, string site, string workstation, string lANID, string dATA01, string lastUpdateBy) {
            Task.ServiceReference2.ERRORRequest inValue = new Task.ServiceReference2.ERRORRequest();
            inValue.Body = new Task.ServiceReference2.ERRORRequestBody();
            inValue.Body.robotName = robotName;
            inValue.Body.client = client;
            inValue.Body.program = program;
            inValue.Body.region = region;
            inValue.Body.site = site;
            inValue.Body.workstation = workstation;
            inValue.Body.lANID = lANID;
            inValue.Body.dATA01 = dATA01;
            inValue.Body.lastUpdateBy = lastUpdateBy;
            return ((Task.ServiceReference2.DADashboardLogSoap)(this)).ERRORAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Task.ServiceReference2.WARNINGResponse Task.ServiceReference2.DADashboardLogSoap.WARNING(Task.ServiceReference2.WARNINGRequest request) {
            return base.Channel.WARNING(request);
        }
        
        public string WARNING(string robotName, string client, string program, string region, string site, string workstation, string lANID, string dATA01, string lastUpdateBy) {
            Task.ServiceReference2.WARNINGRequest inValue = new Task.ServiceReference2.WARNINGRequest();
            inValue.Body = new Task.ServiceReference2.WARNINGRequestBody();
            inValue.Body.robotName = robotName;
            inValue.Body.client = client;
            inValue.Body.program = program;
            inValue.Body.region = region;
            inValue.Body.site = site;
            inValue.Body.workstation = workstation;
            inValue.Body.lANID = lANID;
            inValue.Body.dATA01 = dATA01;
            inValue.Body.lastUpdateBy = lastUpdateBy;
            Task.ServiceReference2.WARNINGResponse retVal = ((Task.ServiceReference2.DADashboardLogSoap)(this)).WARNING(inValue);
            return retVal.Body.WARNINGResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Task.ServiceReference2.WARNINGResponse> Task.ServiceReference2.DADashboardLogSoap.WARNINGAsync(Task.ServiceReference2.WARNINGRequest request) {
            return base.Channel.WARNINGAsync(request);
        }
        
        public System.Threading.Tasks.Task<Task.ServiceReference2.WARNINGResponse> WARNINGAsync(string robotName, string client, string program, string region, string site, string workstation, string lANID, string dATA01, string lastUpdateBy) {
            Task.ServiceReference2.WARNINGRequest inValue = new Task.ServiceReference2.WARNINGRequest();
            inValue.Body = new Task.ServiceReference2.WARNINGRequestBody();
            inValue.Body.robotName = robotName;
            inValue.Body.client = client;
            inValue.Body.program = program;
            inValue.Body.region = region;
            inValue.Body.site = site;
            inValue.Body.workstation = workstation;
            inValue.Body.lANID = lANID;
            inValue.Body.dATA01 = dATA01;
            inValue.Body.lastUpdateBy = lastUpdateBy;
            return ((Task.ServiceReference2.DADashboardLogSoap)(this)).WARNINGAsync(inValue);
        }
    }
}
